### ISSUE TITLE
Gradle ebean generator errors out with ClassNotFound error

### ISSUE THREAD

**Issue by lanxx019** [ebean-orm/querybean-generator#16]
Here is the error message:

```
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':compileJava'.
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.lang.NoClassDefFoundError: io/ebean/annotation/DbJson
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
01:06:18.781 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:242)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:612)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:567)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: io/ebean/annotation/DbJson
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.main.Main.compile(Main.java:553)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:46)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:99)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:52)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:198)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:183)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:120)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:168)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 27 more
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.NoClassDefFoundError: io/ebean/annotation/DbJson
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.ebean.querybean.generator.ProcessingContext.dbJsonField(ProcessingContext.java:115)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.ebean.querybean.generator.ProcessingContext.getPropertyType(ProcessingContext.java:142)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.ebean.querybean.generator.SimpleQueryBeanWriter.addClassProperties(SimpleQueryBeanWriter.java:75)
01:06:18.782 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.ebean.querybean.generator.SimpleQueryBeanWriter.gatherPropertyDetails(SimpleQueryBeanWriter.java:61)
01:06:18.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.ebean.querybean.generator.SimpleQueryBeanWriter.writeRootBean(SimpleQueryBeanWriter.java:88)
01:06:18.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.ebean.querybean.generator.Processor.generateQueryBeans(Processor.java:70)
01:06:18.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.ebean.querybean.generator.Processor.process(Processor.java:51)
01:06:18.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
01:06:18.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
01:06:18.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
01:06:18.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
01:06:18.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
01:06:18.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
01:06:18.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
01:06:18.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.main.Main.compile(Main.java:523)
01:06:18.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 50 more
01:06:18.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.ClassNotFoundException: io.ebean.annotation.DbJson
01:06:18.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 65 more
01:06:18.783 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
```

Copy and paste the config from the gradle plugin website. Not sure if this is the right place to open this.

**Comment by rbygrave** [comment]
We should always look to ask on the forum first (ebean google group).  I'll close this here.
